<?php
/**
 * PETStack configuration TEMPLATE.
 *
 * DO NOT edit this file with real values, and DO NOT put secrets here.
 * This file is committed to git so everyone can see what config is needed.
 *
 * SETUP: copy this file to config.php in the same folder, then fill in
 * your own values below. config.php is gitignored and stays on your
 * machine only. Never commit config.php.
 *
 *   cp src/config.sample.php src/config.php
 */

// ---- Database connection ----

// Host is the same for all local setups.
define('DB_HOST', '127.0.0.1');

// Port depends on your stack:
//   MAMP (Mac)      -> 8889
//   XAMPP (Windows) -> 3306
//   NIH server      -> 3306
define('DB_PORT', '3306');

// Database name. Create a database with this exact name and load the schema.
define('DB_NAME', 'petstack');

// Database user.
//   MAMP / XAMPP local dev -> root
//   NIH server             -> the user IT gives you (not root)
define('DB_USER', 'root');

// Database password:
//   MAMP (Mac)      -> root
//   XAMPP (Windows) -> (leave empty: '')
//   NIH server      -> the password IT gives you
define('DB_PASS', 'CHANGE_ME');

// ---- Security ----

// Secure cookies require HTTPS.
//   Local dev over plain HTTP -> false
//   NIH server with real HTTPS -> true   (IMPORTANT: flip this on at deploy)
define('REQUIRE_SECURE_COOKIES', false);
